AjaxInMvc/Models/Product.cs
namespace AjaxInMvc.Models
{
    public class Product
    {
        public string ProdCode
        {
            get;
            set;
        }
        public string ProdName
        {
            get;
            set;
        }
        public int ProdQty
        {
            get;
            set;
        }
    }
}

AjaxInMvc/Controllers/AjaxController.cs
using AjaxInMvc.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AjaxInMvc.Controllers
{
    public class AjaxController : Controller
    {
        
        public List<Product> InitData()
        {
            List<Product> prodList = new List<Product>();

            Product p1 = new Product { ProdCode = "P001", ProdName = "Mobile", ProdQty = 75 };
            Product p2 = new Product { ProdCode = "P002", ProdName = "Laptop", ProdQty = 125 };
            Product p3 = new Product { ProdCode = "P003", ProdName = "Netbook", ProdQty = 100 };
            prodList.Add(p1);
            prodList.Add(p2);
            prodList.Add(p3);

            return prodList;
        }

        // GET: Ajax
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public PartialViewResult ShowDetails()
        {
            System.Threading.Thread.Sleep(3000); //DEMO ONLY
            string code = Request.Form["ProductCode"];
            var products = InitData();
            Product objView = products.Where(x => x.ProdCode == code).FirstOrDefault();
            return PartialView("_ShowDetails", objView);
        }

        public PartialViewResult GetAllProducts()
        {
            System.Threading.Thread.Sleep(3000); //DEMO ONLY
            List<Product> prodList = InitData();
            return PartialView("_GetAllProducts", prodList);
        }
    }
}

AjaxInMvc/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AjaxInMvc.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

AjaxInMvc/Views/Ajax/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2 class="text-center">Demo Ajax Asp.Net MVC</h2>
<hr />
<h3>1. Ajax.BeginForm</h3>

@using (Ajax.BeginForm("ShowDetails", "Ajax", new AjaxOptions { HttpMethod = "POST", UpdateTargetId = "divResult", InsertionMode = InsertionMode.Replace, LoadingElementId = "loadingElement" }))
{
    <table>
        <tr>
            <td>
                @Html.Editor("ProductCode", new { htmlAttributes = new { @class = "form-control", @placeholder = "Enter Product Code" } })
            </td>
            <td>
                <button type="submit" class="btn btn-primary">Get</button>
            </td>
        </tr>
    </table>
}

@*Product Detail Display Here*@
<div id="loadingElement" style="display:none; color:#f60">
    Loading product detail...
</div>

<div id="divResult"></div>

<h3>2. Ajax.ActionLink </h3>
<p>
    @Ajax.ActionLink("Get All Product", "GetAllProducts", "Ajax", new AjaxOptions
{
    UpdateTargetId = "divResultAll",
    OnBegin = "",
    InsertionMode = InsertionMode.Replace,
    HttpMethod = "GET",
    LoadingElementId = "loadingElement2",
    OnSuccess = "",
    Confirm = "Do you want to get all product?"
}, new { @class = "btn btn-warning" })
</p>
@*Product List Display Here*@
<div id="loadingElement2" style="display:none; color:#f60">
    Loading products...
</div>
<div id="divResultAll"></div>

AjaxInMvc/Views/Ajax/_GetAllProducts.cshtml
@model List<AjaxInMvc.Models.Product>

<table class="table">
    <tr>
        <th>Product Code</th>
        <th>Product Name</th>
        <th>Product Quality</th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>@item.ProdCode</td>
            <td>@item.ProdName</td>
            <td>@item.ProdQty</td>
        </tr>
    }


</table>

AjaxInMvc/Views/Ajax/_ShowDetails.cshtml
@model AjaxInMvc.Models.Product

<div>
    <h4>Product Detail</h4>
    <hr />
    @if (Model == null)
    {
        <p class="text-danger">Invalid product code</p>
    }
    else
    {
        <table>
            <tr>
                <td>Product Code:</td>
                <td>
                    @Model.ProdCode
                </td>
            </tr>
            <tr>
                <td>Product Name:</td>
                <td>
                    @Model.ProdName
                </td>
            </tr>
            <tr>
                <td>Product Quality:</td>
                <td>
                    @Model.ProdQty
                </td>
            </tr>
        </table>
    }
    
</div>

AjaxInMvc/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

AjaxInMvc/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

AjaxInMvc/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

AjaxInMvc/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    <script src="~/Scripts/jquery.unobtrusive-ajax.js"></script>
    @RenderSection("scripts", required: false)
</body>
</html>